import type { EditorThemeClasses } from "lexical";

export const KEEPER_EDITOR_THEME: EditorThemeClasses = {
  heading: {
    h1: "keeper-heading keeper-heading-h1",
    h2: "keeper-heading keeper-heading-h2",
    h3: "keeper-heading keeper-heading-h3",
  },
  list: {
    ol: "keeper-list keeper-list-ol",
    ul: "keeper-list keeper-list-ul",
    listitem: "keeper-list-item",
    checklist: "keeper-list keeper-checklist",
    listitemChecked: "keeper-check-item keeper-check-item-checked",
    listitemUnchecked: "keeper-check-item keeper-check-item-unchecked",
    nested: {
      listitem: "keeper-nested-list-item",
    },
  },
  code: "keeper-code",
  codeHighlight: {
    attr: "keeper-token-attr",
    boolean: "keeper-token-constant",
    builtin: "keeper-token-builtin",
    "class-name": "keeper-token-class",
    comment: "keeper-token-comment",
    constant: "keeper-token-constant",
    deleted: "keeper-token-deleted",
    doctype: "keeper-token-comment",
    function: "keeper-token-function",
    inserted: "keeper-token-inserted",
    keyword: "keeper-token-keyword",
    namespace: "keeper-token-namespace",
    number: "keeper-token-number",
    operator: "keeper-token-operator",
    prolog: "keeper-token-comment",
    property: "keeper-token-property",
    punctuation: "keeper-token-punctuation",
    regex: "keeper-token-string",
    selector: "keeper-token-selector",
    string: "keeper-token-string",
    symbol: "keeper-token-symbol",
    tag: "keeper-token-tag",
    url: "keeper-token-string",
    variable: "keeper-token-variable",
  },
  quote: "keeper-quote",
  link: "keeper-link",
  table: "keeper-table",
  tableCell: "keeper-table-cell",
  tableCellHeader: "keeper-table-cell-header",
  tableRow: "keeper-table-row",
  tableScrollableWrapper: "keeper-table-scroll",
  tableSelection: "keeper-table-selection",
  text: {
    bold: "keeper-text-bold",
    italic: "keeper-text-italic",
    underline: "keeper-text-underline",
    code: "keeper-inline-code",
  },
};
