#!/usr/bin/env node
/**
 * build-viewers.js
 *
 * Reads the minified epub.js and pdfjs-dist sources from node_modules and
 * writes them as TypeScript string exports that the DocumentPanel component
 * can embed directly into a WebView <script> tag.
 *
 * Run automatically via: npm install (postinstall) or npm run build:viewers
 */

const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.resolve(__dirname, "..");
const OUT_DIR = path.join(ROOT, "src", "components", "editor", "document");

function readDist(relativePath) {
	const fullPath = path.join(ROOT, "node_modules", relativePath);
	if (!fs.existsSync(fullPath)) {
		console.warn(
			`[build-viewers] WARNING: ${fullPath} not found — skipping. Run npm install first.`,
		);
		return null;
	}
	return fs.readFileSync(fullPath, "utf8");
}

function writeBundle(filename, varName, source) {
	if (!source) return;
	const escaped = source
		.replace(/\\/g, "\\\\")
		.replace(/`/g, "\\`")
		.replace(/\$\{/g, "\\${");
	const content = `// AUTO-GENERATED by scripts/build-viewers.js — do not edit manually\nexport const ${varName} = \`${escaped}\`;\n`;
	const outPath = path.join(OUT_DIR, filename);
	fs.mkdirSync(OUT_DIR, { recursive: true });
	fs.writeFileSync(outPath, content, "utf8");
	const kb = Math.round(source.length / 1024);
	console.log(`[build-viewers] wrote ${outPath} (${kb} KB)`);
}

const epubJs = readDist("epubjs/dist/epub.min.js");
writeBundle("epubJsBundle.ts", "EPUB_JS", epubJs);

const pdfJs = readDist("pdfjs-dist/build/pdf.min.mjs");
const pdfJsWorker = readDist("pdfjs-dist/build/pdf.worker.min.mjs");
// Combine worker and main into one self-contained script by inlining the worker.
// pdfjs-dist v4 uses ES modules; we concatenate for WebView use.
if (pdfJs && pdfJsWorker) {
	const combined = `// pdfjs-dist worker (inlined)\n${pdfJsWorker}\n// pdfjs-dist main\n${pdfJs}`;
	writeBundle("pdfJsBundle.ts", "PDF_JS", combined);
}
