import { LexicalEditor } from "@web/ui/LexicalEditor";
import { DrawingPad } from "@web/ui/DrawingPad";
import { BrowserTabStrip } from "@web/adapters/browser/tabs/BrowserTabStrip";
import { BrowserEditorHeader } from "@web/adapters/browser/editor/BrowserEditorHeader";
import { BrowserNoteHistoryModal } from "@web/adapters/browser/editor/BrowserNoteHistoryModal";
import { BrowserDocumentPanel } from "@web/adapters/browser/editor/BrowserDocumentPanel";
import { BrowserVideoPanel } from "@web/adapters/browser/editor/BrowserVideoPanel";
import { BrowserRelatedNotes } from "@web/adapters/browser/editor/BrowserRelatedNotes";
import { BrowserNoteMetadata } from "@web/adapters/browser/editor/BrowserNoteMetadata";
import { BrowserArticlePanel } from "@web/adapters/browser/editor/BrowserArticlePanel";
import { useBrowserEditorSession } from "@web/adapters/browser/editor/useBrowserEditorSession";
import { captureBrowserNoteVersion, deleteBrowserNoteVersions } from "@web/services/noteHistory";
import { pickBrowserFile, saveBytes, savePickedFile } from "@web/services/media";
import { useTabStore } from "@keeper/stores/tabStore";
import { getBrowserNoteSurface, type BrowserNote, type BrowserNoteSurface, loadBrowserNotes, persistBrowserNotes } from "@web/ui/noteRepository";
import { Link, Navigate, Route, Routes, useLocation, useNavigate, useParams } from "react-router-dom";
import { createContext, type FormEvent, type ReactNode, useCallback, useContext, useEffect, useMemo, useState } from "react";

type NotesContextValue = { notes: BrowserNote[]; ready: boolean; createNote(surface?: BrowserNoteSurface): BrowserNote; saveNote(note: BrowserNote): Promise<void>; deleteNote(id: string): Promise<void>; notify(message: string): void };
const NotesContext = createContext<NotesContextValue | null>(null);
const TYPES: BrowserNoteSurface[] = ["note", "document", "video", "drawing"];
function useNotes() { const value = useContext(NotesContext); if (!value) throw new Error("Missing Vite notes provider"); return value; }
function typeLabel(type: BrowserNoteSurface) { return ({ note: "Note", document: "Document", video: "Video", drawing: "Drawing" })[type]; }
function changedNote(previous: BrowserNote, next: BrowserNote) { return previous.title !== next.title || previous.content !== next.content || previous.noteType !== next.noteType || previous.isPinned !== next.isPinned || previous.attachment !== next.attachment || previous.attachedVideo !== next.attachedVideo || previous.resourceUrl !== next.resourceUrl || previous.status !== next.status; }

function AppShell({ children }: { children: ReactNode }) {
	const { notes, createNote } = useNotes(); const [drawerOpen, setDrawerOpen] = useState(false); const navigate = useNavigate(); const location = useLocation();
	const tabs = useTabStore((state) => state.tabs); const activeTabId = useTabStore((state) => state.activeTabId); const activateTab = useTabStore((state) => state.activateTab); const closeTab = useTabStore((state) => state.closeTab); const pinTab = useTabStore((state) => state.pinTab);
	function newNote(type: BrowserNoteSurface = "note") { const note = createNote(type); navigate(`/editor/${note.id}`); }
	function selectTab(tab: (typeof tabs)[number]) { activateTab(tab.id); navigate(`/editor/${tab.noteId}`); }
	function removeTab(tabId: string) { closeTab(tabId); const next = useTabStore.getState().tabs.find((tab) => tab.id === useTabStore.getState().activeTabId); if (location.pathname !== "/") navigate(next ? `/editor/${next.noteId}` : "/"); }
	return <div className="app-shell"><aside className={`drawer ${drawerOpen ? "drawer--open" : ""}`} aria-label="Keeper navigation"><div className="drawer__brand"><Link to="/" onClick={() => setDrawerOpen(false)}>Keeper</Link></div><nav><Link to="/" onClick={() => setDrawerOpen(false)}>Home</Link><Link to="/suggested-mocs" onClick={() => setDrawerOpen(false)}>Suggested MOCs</Link></nav><div className="drawer__section"><span>Recent notes</span>{notes.slice(0, 6).map((note) => <Link key={note.id} to={`/editor/${note.id}`} onClick={() => setDrawerOpen(false)}>{note.title || "Untitled"}</Link>)}</div></aside>{drawerOpen ? <button type="button" aria-label="Close navigation" className="drawer-backdrop" onClick={() => setDrawerOpen(false)} /> : null}<div className="app-main"><header className="app-header"><button type="button" className="icon-button" aria-label="Open navigation" onClick={() => setDrawerOpen(true)}>☰</button><Link className="app-header__title" to="/">Keeper</Link><div className="new-menu"><button type="button" className="button" onClick={() => newNote()}>New note</button><button type="button" className="icon-button" aria-label="New drawing" onClick={() => newNote("drawing")}>✎</button></div></header><BrowserTabStrip tabs={tabs} activeTabId={activeTabId} activeView={location.pathname === "/" ? "home" : "note"} onActivateHome={() => navigate("/")} onActivateTab={selectTab} onCloseTab={removeTab} onTogglePin={pinTab} />{children}</div></div>;
}

function HomeRoute() {
	const { notes, createNote, deleteNote, saveNote } = useNotes(); const navigate = useNavigate(); const [query, setQuery] = useState(""); const [filter, setFilter] = useState<"all" | BrowserNoteSurface>("all"); const [draft, setDraft] = useState("");
	const filtered = notes.filter((note) => (filter === "all" || getBrowserNoteSurface(note) === filter) && `${note.title}\n${note.content}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()));
	function create(type: BrowserNoteSurface = "note") { const note = createNote(type); navigate(`/editor/${note.id}`); }
	function quickCreate(event: FormEvent) { event.preventDefault(); if (!draft.trim()) return; const note = createNote(); saveNote({ ...note, title: draft.trim() }); setDraft(""); navigate(`/editor/${note.id}`); }
	return <main className="page home-page"><section className="home-toolbar"><form onSubmit={quickCreate} className="quick-composer"><input value={draft} onChange={(event) => setDraft(event.target.value)} placeholder="Take a note…" aria-label="Quick note title" /><button type="submit" className="button">Create</button></form><input className="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search notes" aria-label="Search notes" /></section><div className="filter-row" aria-label="Note filters"><button type="button" className={filter === "all" ? "filter filter--selected" : "filter"} onClick={() => setFilter("all")}>All</button>{TYPES.map((type) => <button type="button" key={type} className={filter === type ? "filter filter--selected" : "filter"} onClick={() => setFilter(type)}>{typeLabel(type)}</button>)}</div><div className="home-heading"><div><p className="eyebrow">Browser route</p><h1>Notes</h1></div><div className="note-type-actions">{TYPES.slice(1).map((type) => <button type="button" key={type} onClick={() => create(type)}>{typeLabel(type)}</button>)}</div></div>{filtered.length ? <section className="note-grid" aria-label="Notes">{filtered.map((note) => <article key={note.id} className="note-card"><Link to={`/editor/${note.id}`}><span className="note-card__type">{typeLabel(getBrowserNoteSurface(note))}</span><h2>{note.title || "Untitled"}</h2><p>{note.content.replace(/[#*`]/g, "").slice(0, 140) || "Empty note"}</p></Link><footer><time>{new Date(note.lastUpdated).toLocaleDateString()}</time><button type="button" onClick={() => saveNote({ ...note, isPinned: !note.isPinned })}>{note.isPinned ? "Unpin" : "Pin"}</button><button type="button" onClick={() => deleteNote(note.id)}>Delete</button></footer></article>)}</section> : <section className="empty-state"><h2>No notes found</h2><p>Create note. Browser storage ready.</p><button type="button" className="button" onClick={() => create()}>Create note</button></section>}</main>;
}

function SpecialEditor({ note, onChange }: { note: BrowserNote; onChange: (change: Partial<BrowserNote>) => void }) {
	if (note.noteType === "drawing") return <DrawingPad value={note.content} onChange={(content) => onChange({ content })} />;
	if (note.attachedVideo !== null) return note.attachedVideo ? <BrowserVideoPanel url={note.attachedVideo} onDismiss={() => onChange({ attachedVideo: null })} /> : <section className="special-editor"><label>Video URL<input aria-label="Video URL" value={note.attachedVideo} onChange={(event) => onChange({ attachedVideo: event.target.value })} placeholder="https://…" /></label></section>;
	return note.attachment ? <BrowserDocumentPanel attachmentPath={note.attachment} noteId={note.id} onDismiss={() => onChange({ attachment: null })} onPositionChange={(path, position) => onChange({ documentPositions: { ...(note.documentPositions ?? {}), [path]: position } })} /> : <section className="special-editor"><p>Pick a PDF or ePub from editor toolbar.</p></section>;
}

function BrowserTemplatePicker({ open, templates, onApply, onDismiss }: { open: boolean; templates: BrowserNote[]; onApply: (markdown: string) => void; onDismiss: () => void }) {
	if (!open) return null;
	return <div className="browser-history-backdrop" role="presentation" onMouseDown={onDismiss}><dialog className="browser-history-modal" open aria-labelledby="template-title" onMouseDown={(event) => event.stopPropagation()}><header><div><h2 id="template-title">Insert template</h2><p>Choose a template note</p></div><button type="button" aria-label="Close templates" onClick={onDismiss}>×</button></header>{templates.length ? <ul className="browser-history-list">{templates.map((template) => <li key={template.id}><button type="button" className="browser-history-entry" onClick={() => onApply(template.content)}><strong>{template.title || "Untitled"}</strong><span>{template.content.slice(0, 80) || "Empty template"}</span></button></li>)}</ul> : <p className="browser-history-loading">No templates yet. Change a note type to Template first.</p>}</dialog></div>;
}

function EditorRoute() {
	const { noteId = "" } = useParams(); const { notes, saveNote, deleteNote, notify } = useNotes(); const navigate = useNavigate(); const note = notes.find((item) => item.id === noteId); const fallbackNote = useMemo<BrowserNote>(() => ({ id: noteId, title: "", content: "", noteType: "note", isPinned: false, lastUpdated: 0, modified: null, status: null, createdAt: null, completedAt: null, attachment: null, attachedVideo: null, resourceUrl: null, documentPositions: null }), [noteId]); const persistence = useMemo(() => ({ save: saveNote, remove: deleteNote }), [saveNote, deleteNote]); const session = useBrowserEditorSession(note ?? fallbackNote, persistence); const local = session.note; const [historyOpen, setHistoryOpen] = useState(false); const [templateOpen, setTemplateOpen] = useState(false); const [relatedOpen, setRelatedOpen] = useState(false); const [articleOpen, setArticleOpen] = useState(false); const [templateCommand, setTemplateCommand] = useState<{ markdown: string; timestamp: number } | null>(null); const openTab = useTabStore((state) => state.openTab); const updateTabTitle = useTabStore((state) => state.updateTabTitle); const tabs = useTabStore((state) => state.tabs); const localNoteId = note?.id; const localTitle = local.title || "Untitled";
	useEffect(() => { if (localNoteId) openTab(localNoteId, localTitle); }, [localNoteId, localTitle, openTab]);
	useEffect(() => { if (!localNoteId) return; const tab = tabs.find((item) => item.noteId === localNoteId); if (tab && tab.title !== localTitle) updateTabTitle(tab.id, localTitle); }, [localNoteId, localTitle, tabs, updateTabTitle]);
	useEffect(() => { if (!note) return; const timer = window.setTimeout(() => { void session.save().catch(() => notify("Autosave failed.")); }, 800); return () => window.clearTimeout(timer); }, [note, notify, session.save]);
	if (!note) return <main className="page"><section className="empty-state"><h1>Note not found</h1><Link to="/">Back home</Link></section></main>;
	function update(change: Partial<BrowserNote>) { session.patchBrowser(change); }
	async function save() { await session.save(); }
	async function openHistory() { try { await save(); setHistoryOpen(true); } catch { notify("Failed to open version history."); } }
	async function restoreVersion(version: { note: BrowserNote }) { await session.restore(version.note); notify("Version restored."); }
	async function requestImage() { const file = await pickBrowserFile("image/*"); return file ? { src: await savePickedFile(file, "assets"), altText: file.name } : null; }
	async function pasteImage(image: { bytes: Uint8Array; name: string }) { return { src: await saveBytes(image.bytes, image.name, "assets"), altText: image.name }; }
	function attachDocument() { void pickBrowserFile("application/pdf,application/epub+zip,.pdf,.epub").then(async (file) => { if (!file) return; session.patchBrowser({ attachment: await savePickedFile(file, "attachments") }); }); }
	function showVideoModal() { const url = window.prompt("Video URL", local.attachedVideo ?? ""); if (url !== null) session.patchBrowser({ attachedVideo: url }); }
	const surface = getBrowserNoteSurface(local);
	function changeSurface(next: BrowserNoteSurface) { const timestamp = Date.now(); if (next === "drawing") update({ noteType: "drawing", attachment: null, attachedVideo: null, lastUpdated: timestamp, modified: timestamp }); else if (next === "document") update({ noteType: "note", attachment: local.attachment ?? "", attachedVideo: null, lastUpdated: timestamp, modified: timestamp }); else if (next === "video") update({ noteType: "note", attachment: null, attachedVideo: local.attachedVideo ?? "", lastUpdated: timestamp, modified: timestamp }); else update({ noteType: "note", attachment: null, attachedVideo: null, lastUpdated: timestamp, modified: timestamp }); }
	const openWikiLink = (title: string) => { const target = notes.find((item) => item.title.trim().toLocaleLowerCase() === title.trim().toLocaleLowerCase()); if (target) navigate(`/editor/${target.id}`); else notify(`No note named "${title}".`); };
	return <main className="page editor-page"><section className="editor-shell"><BrowserEditorHeader title={session.draft.title} status={session.status} isPinned={session.draft.isPinned} onChangeTitle={(title) => session.patch({ title })} onBlurTitle={() => undefined} onSubmitEditing={() => document.querySelector<HTMLElement>("[aria-label='Note content']")?.focus()} onBack={() => { void save().then(() => navigate("/")); }} onShowHistory={() => { void openHistory(); }} onTogglePin={() => session.patch({ isPinned: !session.draft.isPinned })} onDelete={() => { void session.remove(); navigate("/"); }} /><BrowserNoteMetadata noteType={local.noteType} status={local.status} onNoteType={(noteType) => update({ noteType, status: noteType === "todo" ? (local.status ?? "open") : null })} onStatus={(status) => update({ status })} />{local.noteType === "resource" ? <div className="browser-editor-type"><label htmlFor="resource-url">Resource URL</label><input id="resource-url" aria-label="Resource URL" value={local.resourceUrl ?? ""} onChange={(event) => update({ resourceUrl: event.target.value })} placeholder="https://…" /></div> : null}<div className="browser-editor-type"><label htmlFor="note-surface">View</label><select id="note-surface" aria-label="Note view" value={surface} onChange={(event) => changeSurface(event.target.value as BrowserNoteSurface)}>{TYPES.map((type) => <option key={type} value={type}>{typeLabel(type)}</option>)}</select><button type="button" className="button" onClick={() => { void save(); }}>Save</button></div>{surface === "note" ? <LexicalEditor editorKey={local.id} value={session.draft.content} onChange={(content) => session.patch({ content })} hasAttachment={local.attachment !== null} onAttachDocument={attachDocument} onRemoveAttachment={() => session.patchBrowser({ attachment: null })} onRequestImage={requestImage} onPasteImage={pasteImage} onShowVideoModal={showVideoModal} onInsertTemplateCommand={() => setTemplateOpen(true)} onOpenWikiLink={openWikiLink} onToggleArticle={() => setArticleOpen((value) => !value)} templateCommand={templateCommand} /> : <SpecialEditor note={local} onChange={update} />}{articleOpen && local.resourceUrl ? <BrowserArticlePanel url={local.resourceUrl} onDismiss={() => setArticleOpen(false)} /> : null}<button type="button" className="button" onClick={() => setRelatedOpen((value) => !value)}>{relatedOpen ? "Hide related notes" : "Show related notes"}</button>{relatedOpen ? <BrowserRelatedNotes note={local} notes={notes} onNavigate={(id) => navigate(`/editor/${id}`)} /> : null}<BrowserNoteHistoryModal open={historyOpen} note={local} onDismiss={() => setHistoryOpen(false)} onRestore={restoreVersion} /><BrowserTemplatePicker open={templateOpen} templates={notes.filter((item) => item.noteType === "template")} onDismiss={() => setTemplateOpen(false)} onApply={(markdown) => { setTemplateCommand({ markdown, timestamp: Date.now() }); setTemplateOpen(false); }} /></section></main>;
}

function SuggestedMocsRoute() { const { notes } = useNotes(); const suggestions = useMemo(() => notes.filter((note) => note.content.length > 40).slice(0, 5), [notes]); return <main className="page"><div className="page-heading"><div><p className="eyebrow">MOC screen</p><h1>Suggested MOCs</h1><p>Review browser-generated note groups.</p></div><Link to="/">Back</Link></div><section className="moc-list">{suggestions.length ? suggestions.map((note) => <article key={note.id} className="surface"><h2>{note.title || "Untitled"}</h2><p>Candidate map entry · {typeLabel(getBrowserNoteSurface(note))}</p><Link to={`/editor/${note.id}`}>Open note</Link></article>) : <section className="empty-state"><h2>No suggestions yet</h2><p>Add content to notes. MOC screen works without server classifier.</p></section>}</section></main>; }

function RoutedApp() {
	const [notes, setNotes] = useState<BrowserNote[]>([]); const [ready, setReady] = useState(false); const [toast, setToast] = useState<string | null>(null);
	useEffect(() => { void loadBrowserNotes().catch(() => []).then((loaded) => { setNotes(loaded.sort((a, b) => b.lastUpdated - a.lastUpdated)); setReady(true); }); }, []);
	const commit = useCallback(async (next: BrowserNote[], message: string) => { const previous = new Map(notes.map((note) => [note.id, note])); const versions = next.flatMap((note) => { const old = previous.get(note.id); return old && changedNote(old, note) ? [old] : []; }); await Promise.all(versions.map(captureBrowserNoteVersion)); const sorted = next.sort((a, b) => b.lastUpdated - a.lastUpdated); setNotes(sorted); await persistBrowserNotes(sorted); setToast(message); }, [notes]);
	const value = useMemo<NotesContextValue>(() => ({ notes, ready, createNote: (surface = "note") => { const timestamp = Date.now(); const note: BrowserNote = { id: crypto.randomUUID(), title: "", content: "", noteType: surface === "drawing" ? "drawing" : "note", isPinned: false, lastUpdated: timestamp, modified: timestamp, status: null, createdAt: timestamp, completedAt: null, attachment: surface === "document" ? "" : null, attachedVideo: surface === "video" ? "" : null, resourceUrl: null, documentPositions: null }; void commit([note, ...notes], "Note created locally"); return note; }, saveNote: (note) => commit([note, ...notes.filter((item) => item.id !== note.id)], "Saved locally"), deleteNote: async (id) => { await commit(notes.filter((note) => note.id !== id), "Deleted locally"); await deleteBrowserNoteVersions(id); }, notify: setToast }), [notes, ready, commit]);
	if (!ready) return <main className="startup">Opening browser storage…</main>;
	return <NotesContext.Provider value={value}><AppShell><Routes><Route path="/" element={<HomeRoute />} /><Route path="/editor/:noteId" element={<EditorRoute />} /><Route path="/suggested-mocs" element={<SuggestedMocsRoute />} /><Route path="/documents/:noteId" element={<EditorRoute />} /><Route path="/videos/:noteId" element={<EditorRoute />} /><Route path="/drawing/:noteId" element={<EditorRoute />} /><Route path="*" element={<Navigate to="/" replace />} /></Routes></AppShell>{toast ? <output className="toast" onAnimationEnd={() => setToast(null)}>{toast}</output> : null}</NotesContext.Provider>;
}
export function App() { return <RoutedApp />; }
